spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    virtual-host: ${RABBIT_MQ_USERNAME}
    ssl:
      enabled: false

brevo:
  api-key: ${BREVO_API_KEY}
  url: https://api.brevo.com/v3/smtp/email

server:
  port: 8083

application:
  services:
    user:
      url: http://localhost:8081

