spring:
  application:
    name: booking-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: booking_service
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    virtual-host: ${RABBIT_MQ_USERNAME}
    ssl:
      enabled: false

server:
  port: 8082


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}


application:
  services:
    user:
      url: http://localhost:8081