spring:
  application:
    name: user-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: user_service
    hibernate:
      ddl-auto: update
    open-in-view: false

brevo:
  api-key: ${BREVO_API_KEY}
  url: https://api.brevo.com/v3/smtp/email

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: 3600000

