spring:
  application:
    name: user-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: user_service
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    virtual-host: ${RABBIT_MQ_USERNAME}
    ssl:
      enabled: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: 3600000



